theme: jekyll-theme-cayman
title : "محمدصادق عبداللهی"
description : "برنامه نویس و طراح گرافیک"
lang : "fa"
dir : "rtl"
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: tongqing.qiu@gmail.com
  facebook: 
  flickr: 
  github: tongqqiu
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
